README.md
How to get the exports working if ftools is not working happily with Ruby
=> Update Readme.md with help fixing export error

app/assets/javascripts/mapknitter/Map.js, app/controllers/images_controller.rb, app/views/images/_new.html.erb
=> fixes to client-side distortion, proxying work

app/views/images/_index.html.erb
=> download fix

app/controllers/feeds_controller.rb, app/views/feeds/clean.builder
=> additional clean feed for ifttt

app/views/maps/index.html.erb
* [ I'm not sure what this is.] tests pass -- `rake test`
* [ I believe so...?] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [I believe so. ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes
Thanks!
=> added 'Ask a question' button

app/controllers/maps_controller.rb, app/views/feeds/clean.builder, app/views/maps/map.html.erb
=> feeds fix and map

app/controllers/maps_controller.rb
fixes https://github.com/publiclab/plots2/issues/984
Thanks!
=> testing map map for only non-anonymous

app/controllers/feeds_controller.rb, test/unit/map_test.rb
=> Spam map reduction. Fixes #215

Gemfile.lock
=> Upgrade dependencies.

app/views/maps/_list.html.erb
* [x ] tests pass -- `rake test`
* [ x] code has been rebased on top of latest master (check if another pull request was added recently, and please rebase)
* [x ] pull request is descriptively named and, if possible, multiple commits squashed if they're smaller changes
Thanks!
=> issue #253 (also#252)  flag as spam - mapknitter/app/views/maps/_list.html.erb

app/views/maps/show.html.erb
https://github.com/publiclab/image-sequencer
=> integrate image-sequencer

app/views/maps/_list.html.erb
=> Update _list.html.erb for anon map authors

app/controllers/maps_controller.rb
=> Make "maps by region" readable in JSON API #251

app/views/maps/index.html.erb, bower.json
=> All layers from leaflet-environmental-layers library added .

app/views/maps/index.html.erb
=> Default Mapknitter Markers added

app/views/maps/index.html.erb
=> Full screen support added

bower.json
=> Version updated for LEL .

app/views/maps/index.html.erb, bower.json
=>  Send patch for new LEL library feature . #282 

app/models/map.rb, test/unit/map_test.rb
=> basic map unit tests

app/controllers/maps_controller.rb, app/models/map.rb, test/fixtures/warpables.yml, test/functional/maps_controller_test.rb
=> add image urls to maps json

app/views/map/_list.html.erb
References \#396 (\<=== Add issue number here)
Thanks!
=> Spam button with "ban" icon

app/views/images/_new.html.erb
=> accept uploads from images only

.coveralls.yml, .travis.yml, Gemfile, README.md, test/test_helper.rb
=> Setupcoveralls

app/controllers/images_controller.rb
Deleted the lines from the selection indicated in the issue.
Fixes #404
Thanks!
=> Remove legacy image controller code #404

app/controllers/feeds_controller.rb
=> update syntax of active record query(license method)

README.md
I just realized I used my forks' badge my mistake for updating the readme 
So here's the correct one :smile:
=> Update README.md for codeclimate badge

.travis.yml
Fixes #380  (<=== Add issue number here)
Thanks!
=> Small Travis fix

app/assets/javascripts/uploads.js, app/views/images/_index.html.erb, app/views/layouts/knitter2.html.erb
References \#407 (\<=== Add issue number here)
Thanks!
=> fixed image partial rendering when no images

app/controllers/tags_controller.rb
=> Add a flash notice when adding tags and not logged in

Gemfile, Gemfile.lock, app/assets/bower.json, app/assets/javascripts/application.js, app/assets/javascripts/maps.js, app/assets/stylesheets/header.css.scss, app/assets/stylesheets/style.css.scss, app/views/author/list.html.erb, app/views/images/_new.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/_login.html.erb, app/views/layouts/_login_form.html.erb, app/views/layouts/knitter2.html.erb, app/views/map/_list.html.erb, app/views/maps/_edit.html.erb, app/views/maps/_exports.html.erb, app/views/maps/_list.html.erb, app/views/maps/_search.html.erb, app/views/maps/_sidebar_annotations.html.erb, app/views/maps/_sidebar_exports.html.erb, app/views/maps/index.html.erb, app/views/maps/new.html.erb, app/views/maps/show.html.erb, app/views/tags/_index.html.erb, app/views/users/profile.html.erb, bower.json
Fixes  #377 
(sorry for the confusion, but I had a confusion with my upstream repo, so I moved everything to this new branch).
Hi all, I have some questions/notes:
- Why do we have two `bower.json` files? I wasn't sure which one to use, so I updated both of them;
- In order to make Bootstrap 4 work, I had to install the `popper_js` gem and update `jquery-ui` version;
A little more about this PR: I just updated some of the components that were broken from switching to Bootstrap 4, especially because we will soon update the UI.
Please let me know if I did those version updates correctly, this was my first time doing something like this! :)
Appreciate any help here, I think I didn't forget anything here :shipit:
=> Upgrade app to Bootstrap 4

app/controllers/feeds_controller.rb
Fixes #436  (<=== Add issue number here)
Thanks!
=> Updated ActiveRecord database query style (#436)

app/views/layouts/knitter2.html.erb
Fixes #440  (<=== Add issue number here)
Thanks!
=> Changed the new map modal text

app/views/export/index.html.erb
Fixes #395 (<=== Add issue number here)
GIF for the change:
Thanks!
=> Exports page is now mobile responsive

.travis.yml
=> Prevent multiple builds for PR on travis

Gemfile.lock, README.md
Fixes #492  (<=== Add issue number here)
Thanks!
=> Update Gemfile.lock / README for Ruby 2.4.6

app/controllers/images_controller.rb, config/routes.rb, test/fixtures/annotations.yml, test/functional/export_controller_test.rb, test/functional/images_controller_test.rb, test/functional/tags_controller_test.rb
Fixes  part of #304 
Functional tests for images, tags and exports
=> Increase tests coverage(functional tests)

app/views/layouts/knitter2.html.erb
Fixes #474  (<=== Add issue number here)
* [] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
Thanks!
=> Added favicon for all pages

app/models/warpable.rb, test/fixtures/maps.yml, test/functional/export_controller_test.rb, test/unit/export_test.rb, test/unit/map_test.rb, test/unit/user_test.rb, test/unit/warpable_test.rb
=> Expand unit tests

CONTRIBUTING.md
Fixes #528  (<=== Add issue number here)
See file here for easy reference: https://github.com/publiclab/mapknitter/blob/main/CONTRIBUTING.md
Saw a formatting issue where markdown ## syntax was left behind and decided to fix up the rest of the file too.
Thanks!
=> Update Contributing.md syntax mistake

MYSQL.md
Add linux instructions suggested on https://github.com/publiclab/mapknitter/issues/307#issuecomment-477395391
=> Add linux specific mysql  installations instructions

app/controllers/annotations_controller.rb, app/controllers/application_controller.rb, app/controllers/comments_controller.rb, app/controllers/export_controller.rb, app/controllers/feeds_controller.rb, app/controllers/images_controller.rb, app/controllers/maps_controller.rb, app/controllers/sessions_controller.rb, app/controllers/tags_controller.rb, app/controllers/users_controller.rb, app/controllers/utility_controller.rb, app/models/comment.rb, app/models/export.rb, app/models/map.rb, app/models/node.rb, app/models/tag.rb, app/models/user.rb, app/models/warpable.rb, app/models/way.rb, test/functional/maps_controller_test.rb
Fixes part of #527 and code some cleanup
=> (WIP)Move some controller code to models

app/views/comments/_comment.html.erb
Fixes #529  (<=== Add issue number here)
Before:
After:
Thanks!
=> Comment card design

Gemfile, Gemfile.lock, config/skylight.yml
Will provide visibility on performance!
=> Add Skylight monitoring service (thanks!)

Gemfile, app/controllers/application_controller.rb, app/controllers/feeds_controller.rb, app/controllers/images_controller.rb, app/controllers/maps_controller.rb, app/controllers/tags_controller.rb, test/fixtures/maps.yml, test/fixtures/users.yml, test/functional/feeds_controller_test.rb, test/functional/maps_controller_test.rb
=> Refactoring controllers

app/controllers/sessions_controller.rb, config/config.yml.example, test/functional/feeds_controller_test.rb, test/functional/images_controller_test.rb, test/functional/sessions_controller_test.rb, test/unit/annotation_test.rb, test/unit/comment_test.rb, test/unit/user_test.rb
More test coverage in prep for rails upgrade
=> Increase test coverage++

bower.json
Fixes #542 (<=== Add issue number here)
Thanks!
=> Update LDI to newest release 0.4.2

app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/views/users/index.html.erb
Fixes #517 (<=== Add issue number here)
Thanks!
=> Sort author list 

app/controllers/maps_controller.rb
Fixes #569  (<=== Add issue number here)
Thanks!
=> Search by author name

start.sh
=> Use passenger for sure

Gemfile, Gemfile.lock, app/assets/stylesheets/maps.css.scss, app/views/map/_authors.html.erb, app/views/maps/_list.html.erb, app/views/maps/index.html.erb, app/views/users/index.html.erb, app/views/users/profile.html.erb, db/seeds.rb
=> Reorganize and consolidate templates

app/views/maps/_list.html.erb
Fixes #636  (<=== Add issue number here)
Thanks!
=> Singularization Issue Fixed

Dockerfile, nolimit.xml
This should allow us to tweak Mapknitter ImageMagick Policy
Thanks!
=> Remove resource limits for Imagemagick

app/controllers/sessions_controller.rb, config/application.rb, config/config.yml.example, db/schema.rb, db/seeds.rb, test/functional/sessions_controller_test.rb
Fixes https://travis-ci.org/publiclab/mapknitter/builds/537566288?utm_source=github_status&utm_medium=notification from PR #629
Thanks!
================================================
Problem - developers that name their testing database something different from the development db will receive …
=> Functional tests - testing env fix

app/views/layouts/_header.html.erb
Fixes #508  (<=== Add issue number here) (originally discovered by @divyabaid16 for a different search bar but that one has since been removed)
Thanks!
=> header search bar stays together

app/assets/javascripts/mapknitter/Map.js
https://github.com/publiclab/Leaflet.DistortableImage/pull/243
=> briefly turn off keymapper until bug is resolved

app/assets/stylesheets/maps.css.scss
Fixes #617  (<=== Add issue number here)
Now, the entire page does not scroll.
GIF:
Thanks!
=> Sidebar content scroll added

app/assets/stylesheets/maps.css.scss
Fixes #673
Screenshot
**Before**
**After**
Thanks!
=> Add margin to sidebar content

app/controllers/sessions_controller.rb
Fixes https://github.com/publiclab/mapknitter/issues/679
=> Fix login problem

README.md
Fixes [#683](https://github.com/publiclab/mapknitter/issues/683)
Thanks!
=> Add stable url in README

app/views/maps/index.html.erb
Fixes #570 (<=== Add issue number here)
Thanks!
=> Display images on home page

app/views/layouts/_login.html.erb, app/views/layouts/_login_form.html.erb, app/views/layouts/_login_modal.html.erb, app/views/maps/index.html.erb
Fixes #716  (<=== Add issue number here)
Thanks!
=> Login ui improvement

README.md
=> Updated Installation Instructions Fixes #711

MYSQL.md, README.md
Fixes #676  (<=== Add issue number here)
Thanks!
=> Update README.md MapKnitter Spelling

MYSQL.md
Fixes #722 (<=== Add issue number here)
Thanks!
=> Fix typo in MYSQL.md 

README.md
Fixes #757 
* [] screenshots/GIFs are attached 📎 in case of UI updation
* [] ask `@publiclab/mapknitter-reviewers` for help, in a comment below
Thanks!
=> Added code of conduct badge in README.md file

app/assets/javascripts/knitter.js
Fixes #739 (<=== Add issue number here)
first-timers-only issue.
Thanks!
=> (AddedMultiLineComments) : Added multi line comments. 

app/controllers/front_ui_controller.rb, app/views/front_ui/_featured_mappers.html.erb, app/views/front_ui/_maps.html.erb, app/views/front_ui/index.html.erb
Follow up for #762 
@jywarren forgot to specify no pagination on the front page
=> unpagination front-page

Gemfile, Gemfile.lock, README.md, install_cloud.sh
Fixes #654  (<=== Add issue number here)
- also addresses `yarn install` issue in https://github.com/publiclab/plots2/issues/5622
Thanks!
=================
Changes:
Pending:
=> update codenvy install script and readme

app/controllers/front_ui_controller.rb, app/views/front_ui/index.html.erb, test/functional/front_ui_controller_test.rb
Addressing #774 and other front page fixes!
Fixes #767
Fixes #773
=> change to featured mappers

app/controllers/maps_controller.rb, app/helpers/front_ui_helper.rb, app/models/warpable.rb, test/unit/warpable_test.rb
fix #742 fix #780
Hooray! Thanks to @cesswairimu and @sashadev-sky -- v helpful!
=> image display fix for #742 #780

app/assets/stylesheets/style.scss, app/controllers/front_ui_controller.rb, app/views/front_ui/_featured_mappers.html.erb, app/views/front_ui/nearby_mappers.html.erb, test/functional/front_ui_controller_test.rb
=> Fix gallery page

app/assets/stylesheets/header.scss, app/views/layouts/_login.html.erb
Fixes #798  (<=== Add issue number here)
Thanks!
=> Hover to logout menu added

app/views/maps/index.html.erb
=> Change ask a question url

.codecov.yml, app/assets/javascripts/application.js, app/assets/stylesheets/style.scss, app/views/front_ui/index.html.erb, package.json, yarn.lock
=> final front page tweaks

docker-compose.yml
=> Disable non functional js cache

app/views/front_ui/index.html.erb
=> "Make a map" button and final tweaks

yarn.lock
=> bump ldi version

config/application.rb
#835
Short term fix, we need all domains
=> Allow frames from publiclab.org

start.sh
=> Precompiling assets before serving passenger

Makefile, start.sh
=> Improving Jenkins startup script

db/seeds.rb
=> Removed the line causing problems and re-enabled loading of maps

app/controllers/maps_controller.rb
=> Allow iframes to use maps embeds

Makefile, lib/tasks/db.rake, start.sh
=> Fix missing steps for Jenkins

README.md
added new badge (first-timers-only-friendly) to the README file.
Fixes #687 (<=== Add issue number here)
Thanks!
=> Update to README.md (added badge first-timers-only-friendly)

Dockerfile, Makefile
Patching https://github.com/publiclab/mapknitter/pull/853 and https://github.com/publiclab/mapknitter/pull/803
Thanks!
=> Patch #803 and #853

package.json, yarn.lock
Fixes #855 (<=== Add issue number here)
Thanks!
=> Remove 2nd easybutton dependency

app/assets/javascripts/mapknitter/Map.js, package.json, yarn.lock
=> Update LDI to 0.6.3

README.md
=> Chat-in-different-ways button 

MYSQL.md, README.md
See ongoing discussion about installation for macOS mojave in #622 (<=== Add issue number here)
Thanks!
=> Update installation docs

README.md
Fixes #875  (<=== Add issue number here)
Thanks!
=> Running test on one file added in README.md

docker-compose.yml
=> Update docker version

app/controllers/maps_controller.rb, app/models/map.rb, test/fixtures/tags.yml, test/functional/maps_controller_test.rb, test/unit/map_test.rb
=> Tweaks to maps per region

app/views/front_ui/index.html.erb
=> Lower zoom level

app/views/front_ui/anonymous.html.erb, app/views/front_ui/index.html.erb, config/routes.rb
Fixes #719 
https://github.com/publiclab/mapknitter/issues/719#issuecomment-509428687
Thanks!
=> Anonymous map option added

app/views/front_ui/about.html.erb
=> Extra leaflet line removed

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/images_controller.rb, app/models/warpable.rb, app/views/images/_index.html.erb, config/environments/test.rb, config/initializers/paper_trail.rb, config/routes.rb, db/migrate/20190715092943_create_versions.rb, db/migrate/20190716071842_add_count_version_to_warpables.rb, test/functional/images_controller_test.rb
Fixes #682  (<=== Add issue number here)
Find the attached screenshot:
Thanks!
=> Version tracking of images

lib/exporter.rb
=> Add default value for bands string in exporter

app/views/front_ui/_maps.html.erb
=> Fix images urls

config/environments/production.rb
Addresses #916 i hope...
https://github.com/lautis/uglifier#rails
=> uglifier gem harmony flag for es6

app/views/map/_leaflet.html.erb
=> Fixes #889 - Update initializers to class factory syntax

app/views/maps/_statistics.html.erb
Fixes #897   (<=== Add issue number here)
* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
* [x ] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [ x] code is in uniquely-named feature branch and has no merge conflicts 📁
Please be sure you've reviewed our contribution guidelines at …
=> Fixed repeated word in Statistics page issue #897

app/assets/javascripts/application.js
=> Download popup added 

config/initializers/paper_trail.rb
Fixes #915  (<=== Add issue number here)
Thanks!
=> Database migration - Paper trails error

app/assets/stylesheets/sidebar.css, app/views/images/_index.html.erb
The button is removed:
Sort option is made better:
Thanks!
=> UI improvements: version tracking and other in the sidebar

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, config/environments/test.rb, db/schema.rb, test/system/images_test.rb, test/test_helper.rb
=> Fix image placement

Makefile
=> Remove reference to aws example in Makefile

app/controllers/maps_controller.rb
=> fix for new map creation

app/assets/javascripts/channels/concurrent_editing.js, app/models/warpable.rb
Re: #1041, updates path from `/maps/SLUG` to `/maps/SLUG/edit`
=> Websockets slug fix

README.md
Builds on #819 (<=== Add issue number here)
Thanks!
=> Update README.md Installation Readability

app/controllers/maps_controller.rb, app/models/map.rb, app/views/maps/show.html.erb
Fixes #158 
locally with `rake test`
=> Add map authors in show page

app/views/front_ui/about.html.erb
Corrected issue on about.html.erb
Fixes #1057  (<=== Add issue number here)
* [x ] PR is descriptively titled 📑 and links the original issue above 🔗
* [ x] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
* [x ] code is in uniquely-named feature branch and has no merge conflicts 📁
Please be sure you've reviewed our contribution guidelines at …
=> Updated about.html.erb

README.md
=> Add a depth description in README

app/views/maps/_statistics.html.erb
Fixes #1098  (<=== Add issue number here)
Thanks!
=> Aligning the about.html statistics partial. Resolves issue #1098

public/sorter.html
=> Remove the stray end of script tag

app/assets/javascripts/application.js, app/assets/javascripts/mapknitter/Map.js, package.json, yarn.lock
=> new multi-exporter working

app/views/map/_leaflet.html.erb
This PR resolves #888
@sashadev-sky requesting review :)
=> REFACTOR: Leaflet initializers to use class factory syntax

db/migrate/20191214062147_add_index_for_warpable_map_id.rb, db/schema.rb, db/schema.rb.example
I believe this should help with the performance issues we've seen recently! (tracked internally at https://github.com/jywarren/web/issues/253).
Thanks!
=> Add index to warpables for performance

app/assets/javascripts/mapknitter/Map.js
=> Sidebar deselection logic

app/views/maps/new.html.erb
Fixes #1025
@publiclab/mapknitter-reviewers 
Hi, this pull request will warn anonymous users when they decide to make their map that they will no longer be able to edit it. On the other hand, it does not warn logged in users who can edit their maps.
What do you think?
Thanks! :+1:
=> add confirmation for map submit

app/assets/stylesheets/style.scss, app/views/layouts/knitter2.html.erb
Fixes #1194 
This is pull request for First timers issue 1194 where margin between buttons is added.
Thanks!
=> added margin between buttons

app/assets/stylesheets/header.scss
Fixes #1187 
Horizontal scrollbar has been removed   
Thanks
=> removed hoizontal scroll

app/views/layouts/_header.html.erb
Fixes #1178 
All changes has been made according to issue description.
Thanks!
=> Fix navigation search bar styling

README.md
Fixes #1146 (<=== Add issue number here)
=> Remove sudo from yarn installation command

README.md
=> Added Code of Conduct in README

app/controllers/front_ui_controller.rb, app/views/front_ui/_maps.html.erb
fixes https://github.com/publiclab/mapknitter/issues/1267
=> adjust pagination param for gallery and search pages

app/models/map.rb, lib/not_at_origin_validator.rb
=> Fixing origin validation

config/initializers/recaptcha.rb.example, start.sh
Fixes deployment issue with not finding this value.
Thanks!
=> Add environment variables for RECAPTCHA

config/initializers/paper_trail.rb
=> PaperTrail.config.version_limit = 20

app/controllers/front_ui_controller.rb
=> fix head 200, content_type: "text/html" in front_ui_controller.rb

app.yaml, cloudbuild.yaml
This is to allow automation to the google cloud servers. Should not affect otherwise
Thanks!
=> Automate deployment to appengine

.travis.yml
=> Update .travis.yml to try to fix docker build issue

app/controllers/maps_controller.rb, config/routes.rb
=> Redirect /maps to /gallery

app/views/layouts/application.html.erb
=> Passing CSRF token from frontend

.travis.yml, README.md, app/assets/javascripts/mapknitter/Map.js, db/schema.rb, db/schema.rb.example, package.json, test/channels/connection_test.rb, yarn.lock
Fixes #1379 (<=== Add issue number here)
Thanks!
============================
- Remove extra spaces from README.md
- Update deprecated syntax `assert_equal nil, connection` -> `assert_nil connection`
- Add `yarn config set ignore-engines true` to `.travis.yml`
- Add  "node": ">=10.0.0" to engines …
=> Update ldi dependency

app/views/maps/new.html.erb
=> Add "use current location" button to new map page

cloudbuild.yaml
Fixes https://github.com/steviepubliclab/web/issues/284
=> Fix autodeploy

Gemfile.lock
=> Updated Gemfile.lock to fix asset precompilation

Gemfile.lock, production
=> Work around expired key for our custom GDAL package

config/application.rb
Fixes #1535 (<=== Add issue number here)
Thanks!
=> Add CORS headers

.gitpod.dockerfile, .gitpod.yml, config/application.rb, config/database.yml.gitpod
Parallel work in https://github.com/publiclab/mapknitter/pull/1537  to support https://github.com/publiclab/mapknitter/pull/1534
=> Introduce Gitpod to migration work

.gitpod.dockerfile, .gitpod.yml, config/database.yml.gitpod
in parallel to #1534 
re: https://github.com/publiclab/plots2/blob/main/config/database.yml.gitpod and https://github.com/publiclab/plots2/blob/main/.gitpod.yml
=> Set up Gitpod

start.sh
Based on https://github.com/publiclab/plots2/blob/883e081e0bbbd7cd25332798a4b27404f67f1035/start.sh#L5-L6
=> add yarn install to start.sh

app/views/front_ui/index.html.erb, app/views/maps/_cloud_exports.html.erb, package.json
fixes https://github.com/publiclab/leaflet-environmental-layers/issues/601
Added to LEL in https://github.com/publiclab/leaflet-environmental-layers/pull/326
```
<script src="../node_modules/leaflet-google-places-autocomplete/src/js/leaflet-gplaces-autocomplete.js"></script>
<link rel="stylesheet" href="../node_modules/leaflet-google-places-autocomplete/src/css/leaflet-gplaces-autocomplete.css">
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAOLUQngEmJv0_zcG1xkGq-CXIPpLQY8iQ&libraries=places"></script>
```
> We're happy to help you get this ready -- don't be …
=> add Google Places search control to Leaflet

app/assets/javascripts/mapknitter/Map.js
fixes #1280
This should then start up zoomed to all placed images: https://mapknitter.org/maps/stavanger2013/edit
=> adjust map images fitbounds on startup

README.md
=> fix: add rvm-ruby-install fix for macOS Big Sur users

README.md
=> fix: add forking and improve installation process

README.md
=> fix: fixed typos and sentence structure issues

app/views/layouts/_header.html.erb
Fixes #1650  (<=== Add issue number here)
Thanks!
=> fixed search length character less than 3

app/assets/stylesheets/style.scss, app/views/front_ui/_maps.html.erb, app/views/front_ui/gallery.html.erb
Fixes #1638  (<=== Add issue number here)
As we don't have the access to the database that's why we are not able to fetch the live data. 
=> Redesigned card

lib/tasks/attachment_tasks.rake, lib/tasks/db.rake
=> Correct console messages and errors in rake tasks

app/assets/stylesheets/style.scss, app/views/front_ui/_maps.html.erb
Fixes #1641 
**Enhanced image count in card details**
**Before** 
**After**
=> Enhanced image count in card details

app/assets/stylesheets/application.scss, app/assets/stylesheets/footer.scss, app/assets/stylesheets/style.scss, app/views/front_ui/index.html.erb, app/views/layouts/_footer.html.erb
Fixes #1632 (<=== Add issue number here)
Website---https://mapknitter.org/
https://user-images.githubusercontent.com/67657066/162292000-33f1e219-e8b5-41e5-88c3-27e0a73189f7.mp4
https://user-images.githubusercontent.com/67657066/162293878-d8987f40-322a-4add-963e-c0d42590aca6.mp4
Thanks!
=> Footer redesign

app/views/images/_new.html.erb
Fixes #1675 (<=== Add issue number here)
Thanks!
=> Fixed url link on image upload modal #1675

dockerfiles/development, dockerfiles/production
This is to help solve the issue that assets don't compile when deploying to production
=> Upgrade to Node 16

app/assets/bower.json, app/assets/javascripts/application.js, app/assets/javascripts/maps.js, app/views/front_ui/index.html.erb, package.json, yarn.lock
Reverts publiclab/mapknitter#1692 to fix https://github.com/publiclab/mapknitter/issues/1695
=> Revert "removed refs to jquery-ui"

.github/workflows/tests.yml, app/assets/javascripts/application.js, app/views/front_ui/index.html.erb, app/views/maps/edit.html.erb, app/views/maps/new.html.erb, app/views/tags/index.html.erb, lib/not_at_origin_validator.rb, test/system/maps_test.rb
System test fixes https://github.com/publiclab/mapknitter/issues/1688
=> system test for map location autocompletion

README.md
=> Update Staging urls

config/application.rb, config/initializers/sentry.rb
=> moved sentry config to /config/initializers/sentry.rb

Dockerfile
This is an attempt to force the use of Dockerfile for custom flex environment in appegine
=> Just a copy of dockerfiles/production in Dockerfile

public/404.html, public/422.html, public/500.html, public/offline.html, public/sorter.html
=> Replace <html> tags with <html lang="en">

app/views/layouts/application.html.erb
=> add sentry js

app/controllers/maps_controller.rb, app/controllers/spam_controller.rb, config/routes.rb, test/controllers/maps_controller_test.rb, test/controllers/spam_controller_test.rb, test/integration/routes_test.rb
=> feat: 🎸 method to batch-delete multiple maps (no interface yet)

.rubocop.yml, app/controllers/spam_controller.rb, app/controllers/tags_controller.rb, app/models/map.rb, app/models/warpable.rb, test/test_helper.rb
Run codecov on CI only and rubocop offenses fixes
=> remove local codecov reports & rubocop offenses fixes

app/controllers/spam_controller.rb, config/routes.rb, test/controllers/spam_controller_test.rb, test/integration/routes_test.rb
=> feat: 🎸 methods to ban single user and batch-ban multiple users (no interface yet)

app/controllers/application_controller.rb, app/controllers/feeds_controller.rb, app/controllers/front_ui_controller.rb, app/controllers/maps_controller.rb, app/controllers/tags_controller.rb, app/controllers/users_controller.rb, app/helpers/application_helper.rb, app/models/map.rb, app/models/tag.rb, app/models/user.rb, app/views/maps/show.html.erb, app/views/users/profile.html.erb, config/routes.rb, test/controllers/feeds_controller_test.rb, test/controllers/front_ui_controller_test.rb, test/controllers/maps_controller_test.rb, test/controllers/users_controller_test.rb, test/fixtures/tags.yml, test/models/map_test.rb, test/models/tag_test.rb, test/models/user_test.rb, test/system/spam_mgt_test.rb
=> feat: 🎸 adjust existing fetch map and user endpoints to fetch based on status

Dockerfile
Fixes issue running yarn on Docker install
=> Fix node version install

app/controllers/spam_controller.rb, config/routes.rb, test/controllers/spam_controller_test.rb, test/integration/routes_test.rb
=> feat: 🎸 methods to unban single user and batch-unban multiple users (no interface yet) 

app/controllers/application_controller.rb, app/controllers/spam_controller.rb, config/routes.rb, test/controllers/spam_controller_test.rb, test/integration/routes_test.rb
=> feat: 🎸methods to fetch maps on spam management dashboard (no interface yet)
