publiclab/mapknitter

- config/initializers/rack.rb
This is all good for being merged -- fix related to .map files in bower includes, and `rake assets:precompile` -- see https://github.com/FortAwesome/Font-Awesome/issues/6820#issuecomment-195950693.
> rack.rb line for .map files in bower

- app/assets/javascripts/mapknitter/Map.js
- app/views/maps/_sidebar_exports.html.erb
> per-image download button status indicator, close #217

- README.md
- app/models/warpable.rb
Thanks!
ftools has been deprecated since Ruby 1.9.1
> Replace ftools for fileutils (ftools is deprecated)

- Dockerfile
This is the Dockerfile used to deploy Mapknitter locally.
For the record, some hacky tweaks were done to avoid using S3 in local production environment:
https://github.com/icarito/mapknitter/commit/19e0d38dce5b56584c7887ad66abca24dbedca2e
These could moved into configuration to allow friendlier local installation.
> Contribute Dockerfile for working within a container

- app/views/maps/index.html.erb
- bower.json
> Integrating Leaflet-Environmental-Library .

- Gemfile.lock
- app/assets/package-lock.json
- config/initializers/column_definition.rb
- config/initializers/duration.rb
- config/initializers/visitor.rb
- test/fixtures/tags.yml
- test/fixtures/users.yml
> Updates to customize rails / ruby and mySQL version compatibility 

- app/controllers/maps_controller.rb
- app/views/maps/map.html.erb
- test/functional/maps_controller_test.rb
Fixes #250 
The problem was that the user attributes could not be accessed due to the select query. I explicitly selected the required user attribute and that seemed to have fixed it! :tada: 
Here's a screenshot as well,
Thanks!
> Fix map of maps

- app/assets/stylesheets/header.css.scss
- app/views/layouts/_header.html.erb
Bootstrap 3 has a different media query for collapsing the navbar and I just noticed that after @sashadev-sky mentioned that (thanks!). So I added some CSS properties to fix this. I changed the color to the previous one as well, but I didn't re-add the logo because we have some UI improvements to be made soon, so I thought it could wait before re-adding this back.
Also, I tested with the alerts improvement from #383 and it looks like it's okay now:
> Fix navbar medium screen sizes collapse behavior + change color

- README.md
> fixed outdated ruby versions listed in README #412

- Makefile
- app/controllers/application_controller.rb
- docker-compose.yml
- start.sh
Some ideas taken from #363 - deployed now on http://mapknitter.laboratoriopublico.org/ !
This has been tested in unstable please merge!
Thanks!
> Deployment tweaks including Makefile and start script

- app/models/map.rb
References \#403
I installed the application locally, but `rake test` is failing on a `gdal2tiles.py` command (see [here](https://github.com/publiclab/mapknitter/issues/403#issuecomment-475082495)).
> Refactor bbox() function's ActiveRecord query to new Rails syntax #403

- app/assets/javascripts/maps.js
This closes issue #441 "Change comment count on comment creation via AJAX #441" by incrementing comments-number each time a new comment is added. This would ensure that the counter indicating the number of comments is increased without needing to refresh the page.
To test it: 
1. Visit https://mapknitter.org/maps/test-map-1
2. Add a new comment
3. "0 comments" should change to "1 comments" without needing to refresh the page
> Change comment count on comment creation via AJAX #441

- PULL_REQUEST_TEMPLATE.md
> update pr template

- app/assets/stylesheets/maps.css.scss
Fixes #391  (<=== Add issue number here)
GIF for the change
Thanks!
> Gridview aligned at home page

- .gitignore
- Gemfile
- app/controllers/sessions_controller.rb
- app/views/layouts/_alerts.html.erb
- app/views/layouts/application.html.erb
- app/views/maps/index.html.erb
**Issues solved:** 
------
Thanks!
> Alert improvement and adding byebug gem

- app/assets/stylesheets/maps.css.scss
- app/views/comments/_comment.html.erb
- app/views/export/index.html.erb
- app/views/images/_index.html.erb
- app/views/images/_new.html.erb
- app/views/layouts/knitter2.html.erb
- app/views/map/_annotations.html.erb
- app/views/map/view.html.erb
- app/views/maps/_sidebar_annotations.html.erb
- app/views/maps/_sidebar_exports.html.erb
- app/views/maps/annotate.html.erb
- app/views/maps/index.html.erb
- app/views/maps/new.html.erb
Fixes #487 
Those small issues passed by, I'm glad you noticed them, @jywarren . I ran through the app and I _think_ all the old buttons are fixed now. Thanks!
> Bootstrap 4 small button fixes

- app/controllers/comments_controller.rb
- test/fixtures/comments.yml
- test/fixtures/maps.yml
- test/fixtures/users.yml
- test/fixtures/warpables.yml
- test/functional/comments_controller_test.rb
- test/functional/images_controller_test.rb
- test/functional/maps_controller_test.rb
> Increase test coverage

- Dockerfile
- Gemfile
- Makefile
- README.md
- docker-compose.yml
Here I've rolled back the upgrade to Debian 10 / Buster because the Mysql Gem was having issues with libmariadb-dev. I had to backport Debian 10 packages of GDAL 2.4 but it seems to work much faster now!
Also this PR contains tweaks that are needed for building `unstable` branch as staging for the team to use for testing.
Thanks!
> Roll back to using Debian 9 with custom built GDAL

- Dockerfile
Fixes recent build unreliability.
This should work around slow key distribution and make builds reliable again!
Thanks!
> Choose keyserver known to have our GPG key

- app/views/images/_new.html.erb
Fixes #407,  #257 and #549
Add .show class after fade
In bootstrap4 first tab pane must have .show to make the initial content visible
> Solve image uploads bugs

- app/assets/stylesheets/style.css.scss
Fixes #691  (<=== Add issue number here)
Before:
After:
Thanks!
> Dotted line removed on click

- app/models/map.rb
Fixes https://github.com/publiclab/mapknitter/pull/670#pullrequestreview-247354730 (<=== Add issue number here)
Thanks!
> Reverse map refresh bug

- MYSQL.md
Fixes #723 (<=== Add issue number here)
Thanks!
> Fix grammar mistakes and change wording

- app/assets/javascripts/application.js
Fixes #728 
Hi here is the solution in case someone else faces this issue later
` //= require_tree .` loads all the custom .js from the folder `app/assets/javascripts/`
Since it was at the top of the declarations, the custom js was loaded first.
Because of this,  `Google.js` was loaded before `leaflet` which gave rise to the error `L is not defined `
So be careful about the order in which you're loading the static files!
Thanks!
> Fix map loading

- app/views/layouts/knitter2.html.erb
Fixes #720 (<=== Add issue number here)
Thanks!
> Image added to the post

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/sidebar.css
- app/views/images/_index.html.erb
Fixes #638 (<=== Add issue number here)
GIF for the same:
Thanks!
> Image ordering in sidebar using sorting options

- app/controllers/maps_controller.rb
- app/helpers/front_ui_helper.rb
- app/views/front_ui/gallery.html.erb
- test/functional/maps_controller_test.rb
> Fix search bug

- app/views/front_ui/index.html.erb
- test/functional/front_ui_controller_test.rb
Fixes #800  (<=== Add issue number here)
Before:
After:
* [] tests pass -- look for a green checkbox ✔️ a few minutes after opening your PR -- or run tests locally with `rake test`
Thanks!
> Featured Mappers Mobile Responsive fix

- .travis.yml
> Fixing cache path in between builds

- app/views/front_ui/index.html.erb
- test/integration/front_page_test.rb
Fixes #797  (<=== Add issue number here)
Thanks!
> Small UI fix for All maps

- .codecov.yml
Might fix #810 
The inconsistency is arising from project. Let's try this and see if it fixes the codecov issue
> Turn off project, turn on patch for codecov

- app/assets/stylesheets/sidebar.css
- app/views/images/_index.html.erb
Fixes #796  (<=== Add issue number here)
The option by which the user sorts/orders the image is highlighted.
Thanks!
> Sorting option highlighted in the image sidebar

- .gitignore
IntelliJ IDEs add .idea/ directory to the project so one has to be careful while making a commit, so adding it in gitignore. Although, some of the .idea/ files can be tracked by VCS but let's ignore it for now.
> Exclude .idea directory from tracking

- app/assets/javascripts/mapknitter/Map.js
Fixes #860 (<=== Add issue number here)
Thanks!
> Updated-L.Control.Layers initializer to class factory syntax

- app/controllers/tags_controller.rb
- app/views/tags/index.html.erb
Fixes #807  (<=== Add issue number here)
Thanks!
> Map and gallery template added to tags page

- app/views/maps/index.html.erb
- Delete unnecessary 'new' keyboard
- Fix for methods name
Fixes #929  (<=== Add issue number here)
Thanks!
> Implement factory method syntax

- app/assets/stylesheets/sidebar.css
- app/views/images/_index.html.erb
Fixes #724  (<=== Add issue number here)
GIF:
Thanks!
> Toggle view option for image added in the sidebar

- app/assets/javascripts/channels/concurrent_editing.js
- app/assets/javascripts/mapknitter/Map.js
- app/channels/concurrent_editing_channel.rb
- app/controllers/images_controller.rb
- test/controllers/images_controller_test.rb
Some bug fixes related to #805
> Synch editing add ons

- app/assets/stylesheets/header.scss
Fixes #0970 (<=== Add issue number here)
Thanks!
> Removed the dotted line from OAuth button options

- app/assets/stylesheets/sidebar.css
- app/views/images/_index.html.erb
Fixes #738  (<=== Add issue number here)
As a follow up https://github.com/publiclab/mapknitter/pull/738#issuecomment-515741927 by @gauravano I have made the changes
Thanks!
> Grid view follow up issue

- app/controllers/maps_controller.rb
- app/views/maps/new.html.erb
- app/views/maps/show.html.erb
> preserve coords on making a new map from the view map page

- app/views/maps/show.html.erb
- test/controllers/maps_controller_test.rb
Fixes #1050  (<=== Add issue number here)
Thanks!
> List map tags in view map page (new show page)

- README.md
Fixes #1094 (<=== Add issue number here)
Thanks!
> Issue #1094 - Add window installations

- app/assets/javascripts/mapknitter/Map.js
Fixes part 2 of https://github.com/publiclab/Leaflet.DistortableImage/issues/367 and error from https://github.com/publiclab/mapknitter/issues/1124
I refactored the code to use the new `#replaceTool` function.  I also replaced the variable name `Delete` with `L.DeleteAction` to fix the error in https://github.com/publiclab/mapknitter/issues/1124. 
@gauravano @SidharthBansal @sashadev-sky @IshaGupta18 @cesswairimu @divyabaid16 @jywarren Could you take a look please? Thanks!
> Refactored with #replaceTool and fixed `Delete` error

- start.sh
A user had complained about us not showing a warning when recaptcha is
not configured. This change introduces a warning for users that haven't
configured recaptcha.
Resolves #1112
@cesswairimu @sidntrivedi012 @sashadev-sky  could you review this, please?
Thanks.
> ADD: Recaptcha warning message

- app/assets/stylesheets/style.scss
After #1152, I for some reason restricted the width of the footer to 80% and @tsparksh warned me that it now looks like this:
> ![image](https://user-images.githubusercontent.com/17945250/71669000-ce270300-2d9d-11ea-85a0-8303e3930094.png)
So this pull request is just to remove that css rule so the footer is once again at max width
> fix footer width problem

- app/views/tags/_index.html.erb
Is this something that you had in mind? Here is my button:
Clicking on the button displays the modal with a message:
Resolves #808 
@ananyaarun @cesswairimu @jywarren could you take a look at this? Thanks.
> ADD: "Create a collection" button

- app/assets/stylesheets/style.scss
First Timers is awesome! Added a border for issue #965
Thanks!
> Add border to Authors in gallery template #965

- db/migrate/20191219051509_add_missing_indices.rb
I enabled mysql-slow queries and found a few queries with missing indices. Here is a migration for them!
Thanks!
> Found queries without indices

- docker-compose.yml
Fixes #1208
This is supposed to avoid creation of a ./core file when passenger crashes. It is not a solution to the actual crash but it should avoid breaking the staging build. I will try it on top of current `unstable` first.
Thanks!
> Add limit to avoid core dump file

- app/assets/stylesheets/style.scss
- app/views/layouts/_login_form.html.erb
Fixes #1065 (<=== Add issue number here)
Moves styling from _login_form.html.erb to the stylesheet style.scss
Thanks!
> Move styling to stylesheets for login page

- app/assets/stylesheets/front_ui.scss
- app/views/front_ui/index.html.erb
Fixes #1221  (<=== Add issue number here)
* [ x] PR is descriptively titled 📑 and links the original issue above 🔗
Move styling from front_ui to stylesheets/front_ui
Thanks!
> move the styling on the front_ui/index to stylesheets/front_ui.scss

- config/application.rb
Fixes #1245 i hope! cc @icarito
> add /lib/**/__ to autoload-paths

- config/environments/production.rb
Last deployment broke the exporter in production, this change of settings fixed it.
Thanks!
> [HotFix] Solution to broken exporter

- config/application.rb
This is analogous to https://github.com/publiclab/plots2/pull/7796
It's meant to avoid events from staging to alert admins.
Fixes https://github.com/steviepubliclab/web/issues/268
Thanks!
> Teach Sentry to recognize docker-compose project as environment

- app/assets/stylesheets/style.scss
- app/views/sessions/new.html.erb
Fixes #1183 (<=== Add issue number here)
Adds padding and allignment for contents on the login page
Thanks!
> Rectify login page styling

- app/views/front_ui/index.html.erb
- config/routes.rb
> fix front page map for new LEL version

- app/views/front_ui/_maps.html.erb
- app/views/users/profile.html.erb
> Removed additional will_paginate call on _maps

- config/application.rb
This was a tricky one. Ruby interpreted a trailing comma that I sloppily left behind as meaning to concatenate with the next assigned variable (!). Giving the wrong headers for CORS.
Thanks!
> Fix trailing comma, altered headers. (Fixes CORS)

- app/views/front_ui/_maps.html.erb
Fixes #1182 
Added a "No results found" message wherever we are displaying map lists and no results are available. 
> Add message if no maps available

- app/assets/stylesheets/header.scss
- app/views/layouts/_alerts.html.erb
- app/views/layouts/_header.html.erb
- app/views/layouts/knitter2.html.erb
Fixes #1611  (<=== Add issue number here)
Changed navbar bootstrap class so that it does not overlap with site content, specially notifications.
Before ->
https://user-images.githubusercontent.com/85152262/158656373-25490865-e83d-4762-b30c-6c6cea669368.mp4
After ->
https://user-images.githubusercontent.com/85152262/158656600-b8a488ac-dcb2-4fdb-85ff-df41f9f852fb.mp4
> Remove navbar overlap

- app/views/front_ui/index.html.erb
- package.json
- yarn.lock
Fixes #1174 (<=== Add issue number here)
Scaled homepage modal buttons so that they are of the same height on all screens
https://user-images.githubusercontent.com/85152262/156917991-067a1173-6371-46e2-9c47-139cbb035e7a.mp4
> Scale homepage modal buttons

- app/views/layouts/_header.html.erb
Fixes #1635   (<=== Add issue number here)
Thanks!
> added fix for empty search string

- app/assets/stylesheets/style.scss
- app/views/front_ui/_maps.html.erb
Fixes #1640 
**Added styling to the author's name**
Before
After
> changed author name styling

- package.json
- yarn.lock
Reverts publiclab/mapknitter#1554
> Revert "Bump spin.js from 2.3.2 to 4.1.1" since latest version doesn't work with sprockets (is typescript)

- .github/label-actions.yml
- .github/workflows/process-label-actions.yml
> Update label action

- app/controllers/maps_controller.rb
- db/migrate/20220608115906_add_status_to_users_and_maps.rb
- db/schema.rb
- test/controllers/maps_controller_test.rb
> chore: 🤖 add status columns to maps and users tables

- app/controllers/application_controller.rb
- app/controllers/spam_controller.rb
- app/models/map.rb
- app/models/user.rb
- config/routes.rb
- db/migrate/20220628190519_add_status_update_time_to_users.rb
- db/schema.rb
- test/controllers/spam_controller_test.rb
- test/integration/routes_test.rb
- test/models/map_test.rb
- test/models/user_test.rb
> feat: 🎸 methods and db changes to publish single map and batch-publish multiple maps (no interface yet)

- app/assets/stylesheets/header.scss
Fixes #1656  (<=== Add issue number here)
**Problem**
The About Page of Mapknitter is not responsive according to screen resolution
https://https://mapknitter.org/about
**Before**
https://user-images.githubusercontent.com/67657066/163668837-ed91ebe9-8cb5-4222-98fe-aaad25edddf6.mp4
**After**-->
https://user-images.githubusercontent.com/67657066/163668852-4f799137-115d-4ddf-93f5-01f1e3183207.mp4
> Responsive error of About Page 

- app/views/maps/show.html.erb
Fixes #1625 (<=== Add issue number here)
Before - 
After - 
> Scale map show page buttons 

- app/controllers/spam_controller.rb
- config/routes.rb
- test/controllers/spam_controller_test.rb
- test/integration/routes_test.rb
> feat: 🎸 method to fetch users on spam management dashboard (no interface yet)
